name: Publish to Registry
on:    
  push:
    tags:
      - '*'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install dependencies
      run: npm ci

    - name: Build dependencies
      run: npm run build

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
        name: clabroche/docker-registry/fm-interactive-pricing-component-main
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        registry: docker.pkg.github.com
        tags: "latest,${{ env.STATE_RELEASE_VERSION }}"

  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'clabroche'
        reponame: 'fm-interactive-pricing-component'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
  